In [1]:
import numpy as np
import math
from scipy.linalg import ishermitian

In [2]:
#matrix decomposition function into block matrixes
def matrix11(matrix):
    matrix11 = np.array([[0.] * 1] * 1)
    matrix11[0][0] = matrix[0][0]
    return matrix11

def matrix12(matrix):
    n = int(math.sqrt(matrix.size))
    matrix12 = np.array([[0.] * (n-1)] * 1)
    for i in range(1, n):
        matrix12[0][i-1] = matrix[0][i]
    return matrix12

def matrix21(matrix):
    n = int(math.sqrt(matrix.size))
    matrix21 = np.array([[0.] * 1] * (n-1))
    for i in range(1, n):
        matrix21[i-1][0] = matrix[i][0]
    return matrix21

def matrix22(matrix):
    n = int(math.sqrt(matrix.size))
    matrix22 = np.array([[0.] * (n-1)] * (n-1))
    for i in range(1,n):
        for j in range(1, n):
            matrix22[i-1][j-1] = matrix[i][j]
    return matrix22

In [3]:
#make L11 and L21 and L21 transpose(L21T)
def L11(matrix):
    L11 = np.array([[0.] * 1] * 1)
    L11[0][0] = math.sqrt(matrix11(matrix))
    return L11

def L21(matrix):
    n = int(math.sqrt(matrix.size))
    L21 = np.array([[0.] * 1] * (n-1))
    for i in range(n-1):
        L21[i][0] = matrix21(matrix)[i][0] / L11(matrix)[0][0]
    return L21

def L21T(matrix):
    n = int(math.sqrt(matrix.size))
    L21T = np.array([[0.] * (n-1)] * 1)
    for i in range(n-1):
        L21T[0][i] = L21(matrix)[i][0]
    return L21T

In [4]:
#make L21 multiply L21T
def L21L12T(matrix):
    n = int(math.sqrt(matrix.size))
    L21L12T = np.array([[0.] * (n-1)] * (n-1))
    for i in range(n-1):
        for j in range(n-1):
            L21L12T[i][j] += L21(matrix)[i][0] * L21T(matrix)[0][j]
    return L21L12T

In [5]:
#find L 
def L_finder(matrix):
    n = int(math.sqrt(matrix.size))

    L = np.array([[0.] * n] * n)
    L[0][0] += L11(matrix)[0][0]
    for i in range(n-1):
        L[i+1][0] += L21(matrix)[i][0]

    if(n == 1):
        return L
    else:
        for i in range(n-1):
            for j in range(n-1):
                L[i+1][j+1] += L_finder(matrix22(matrix) - L21L12T(matrix))[i][j]
    return L


In [6]:
#make matrix and check qualification
n  = int(input("input the dimension of matrix : "))
entries = []
for i in range (n*n):
    entries.append(float(input()))
matrix = np.array(entries).reshape(n, n)

if(ishermitian(matrix) == False):
   print("this matrix is not hermitan, please enter a hermitan matrix")
else:
    flag = True
    for i in range(1,n+1):
        a = np.array([[0.] * i] * i)
        for j in range(i):
            for k in range(i):
                a[j][k] = matrix[j][k]
        if(int(np.linalg.det(a)) <= 0):
            flag = False
    if(flag == False):
        print("this matrix is not positive definite matrix, please enter a positive definite matrix")


In [7]:
#print our matrixes
print("matrix : ")
print(matrix)
print("..............................")
print("matrix11 : ")
print(matrix11(matrix))
print("..............................")
print("matrix12 : ")
print(matrix12(matrix))
print("..............................")
print("matrix21 : ")
print(matrix21(matrix))
print("..............................")
print("matrix22 : ")
print(matrix22(matrix))

matrix : 
[[  9.   3.   3.]
 [  3.  17.  21.]
 [  3.  21. 107.]]
..............................
matrix11 : 
[[9.]]
..............................
matrix12 : 
[[3. 3.]]
..............................
matrix21 : 
[[3.]
 [3.]]
..............................
matrix22 : 
[[ 17.  21.]
 [ 21. 107.]]


In [8]:
#print our matrixes
print("L : ")
print(L_finder(matrix))
print("..............................")
print("L Transpose : ")
print(L_finder(matrix).T)
print("..............................")
print("L11 : ")
print(L11(matrix))
print("..............................")
print("L21 : ")
print(L21(matrix))
print("..............................")
print("L21 Transpose : " )
print(L21T(matrix))
print("..............................")
print("L22 : ")
print(L_finder(matrix22(matrix) - L21L12T(matrix)))
print("..............................")
print("L22 Transpose : ")
print(L_finder(matrix22(matrix) - L21L12T(matrix)).T)

L : 
[[3. 0. 0.]
 [1. 4. 0.]
 [1. 5. 9.]]
..............................
L Transpose : 
[[3. 1. 1.]
 [0. 4. 5.]
 [0. 0. 9.]]
..............................
L11 : 
[[3.]]
..............................
L21 : 
[[1.]
 [1.]]
..............................
L21 Transpose : 
[[1. 1.]]
..............................
L22 : 
[[4. 0.]
 [5. 9.]]
..............................
L22 Transpose : 
[[4. 5.]
 [0. 9.]]


/var/folders/gt/ypsmnmx90c32m2w9gjtxk1xm0000gn/T/ipykernel_20528/1754867528.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  L11[0][0] = math.sqrt(matrix11(matrix))


In [9]:
#print our matrixes
print("L21 * L21T : ")
print(L21L12T(matrix))
print("..............................")
print("L22 * L22T : ")
print(matrix22(matrix) - L21L12T(matrix))

L21 * L21T : 
[[1. 1.]
 [1. 1.]]
..............................
L22 * L22T : 
[[ 16.  20.]
 [ 20. 106.]]


/var/folders/gt/ypsmnmx90c32m2w9gjtxk1xm0000gn/T/ipykernel_20528/1754867528.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  L11[0][0] = math.sqrt(matrix11(matrix))


In [10]:
#print the result
print("RESULT :")
print()
print("our matrix :")
print(matrix)
print()
print("L decoposition :")
print(L_finder(matrix))
print()
print("L Transpose decomposition :")
print(L_finder(matrix).T)

RESULT :

our matrix :
[[  9.   3.   3.]
 [  3.  17.  21.]
 [  3.  21. 107.]]

L decoposition :
[[3. 0. 0.]
 [1. 4. 0.]
 [1. 5. 9.]]

L Transpose decomposition :
[[3. 1. 1.]
 [0. 4. 5.]
 [0. 0. 9.]]


/var/folders/gt/ypsmnmx90c32m2w9gjtxk1xm0000gn/T/ipykernel_20528/1754867528.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  L11[0][0] = math.sqrt(matrix11(matrix))
