In [1]:
import numpy as np
import math

In [2]:
#matrix decomposition function into block matrixes
def matrix11(matrix):
    matrix11 = np.array([[0.] * 1] * 1)
    matrix11[0][0] = matrix[0][0]
    return matrix11

def matrix12(matrix):
    n = int(math.sqrt(matrix.size))
    matrix12 = np.array([[0.] * (n-1)] * 1)
    for i in range(1, n):
        matrix12[0][i-1] = matrix[0][i]
    return matrix12

def matrix21(matrix):
    n = int(math.sqrt(matrix.size))
    matrix21 = np.array([[0.] * 1] * (n-1))
    for i in range(1, n):
        matrix21[i-1][0] = matrix[i][0]
    return matrix21

def matrix22(matrix):
    n = int(math.sqrt(matrix.size))
    matrix22 = np.array([[0.] * (n-1)] * (n-1))
    for i in range(1,n):
        for j in range(1, n):
            matrix22[i-1][j-1] = matrix[i][j]
    return matrix22

In [3]:
#make L11 and L21
def L11(matrix):
    L11 = np.array([[0.] * 1] * 1)
    L11[0][0] = 1
    return L11

def L21(matrix):
    n = int(math.sqrt(matrix.size))
    L21 = np.array([[0.] * 1] * (n-1))
    for i in range(n-1):
        L21[i][0] = matrix21(matrix)[i][0] / matrix11(matrix)[0][0]
    return L21

In [4]:
#make U11 and U12

def U11(matrix):
    U11 = np.array([[0.] * 1] * 1)
    U11[0][0] = matrix11(matrix)[0][0] 
    return U11

def U12(matrix):
    n = int(math.sqrt(matrix.size))
    U12 = np.array([[0.] * (n-1)] * 1)
    for i in range(n-1):
        U12[0][i] = matrix12(matrix)[0][i]
    return U12


In [5]:
#make L21 multiply U12
def L21U12(matrix):
    n = int(math.sqrt(matrix.size))
    L21U12 = np.array([[0.] * (n-1)] * (n-1))
    for i in range(n-1):
        for j in range(n-1):
            L21U12[i][j] += L21(matrix)[i][0] * U12(matrix)[0][j]
    return L21U12

In [6]:
#find L 
def L_finder(matrix):
    n = int(math.sqrt(matrix.size))

    L = np.array([[0.] * n] * n)
    L[0][0] += L11(matrix)[0][0]
    for i in range(n-1):
        L[i+1][0] += L21(matrix)[i][0]

    if(n == 1):
        return L
    else:
        for i in range(n-1):
            for j in range(n-1):
                L[i+1][j+1] += L_finder(matrix22(matrix) - L21U12(matrix))[i][j]
    return L


In [7]:
#find U
def U_finder(matrix):
    n = int(math.sqrt(matrix.size))

    U = np.array([[0.] * n] * n)
    U[0][0] += U11(matrix)[0][0]
    for i in range(n-1):
        U[0][i+1] = U12(matrix)[0][i]

    if(n == 1):
        return U
    else:
        for i in range(n-1):
            for j in range(n-1):
                U[i+1][j+1] += U_finder(matrix22(matrix) - L21U12(matrix))[i][j]
    return U

In [8]:
#make matrix
n  = int(input("input the dimension of matrix : "))
entries = []
for i in range (n*n):
    entries.append(float(input()))
matrix = np.array(entries).reshape(n, n)

In [9]:
#print our matrixes
print("matrix : ")
print(matrix)
print("..............................")
print("matrix11 : ")
print(matrix11(matrix))
print("..............................")
print("matrix12 : ")
print(matrix12(matrix))
print("..............................")
print("matrix21 : ")
print(matrix21(matrix))
print("..............................")
print("matrix22 : ")
print(matrix22(matrix))

matrix : 
[[  9.   3.   3.]
 [  3.  17.  21.]
 [  3.  21. 107.]]
..............................
matrix11 : 
[[9.]]
..............................
matrix12 : 
[[3. 3.]]
..............................
matrix21 : 
[[3.]
 [3.]]
..............................
matrix22 : 
[[ 17.  21.]
 [ 21. 107.]]


In [10]:
#print our matrixes
print("L : ")
print(L_finder(matrix))
print("..............................")
print("L11 : ")
print(L11(matrix))
print("..............................")
print("L21 : ")
print(L21(matrix))
print("..............................")
print("L22 : ")
print(L_finder(matrix22(matrix) - L21U12(matrix)))
print("..............................")

L : 
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 1.25       1.        ]]
..............................
L11 : 
[[1.]]
..............................
L21 : 
[[0.33333333]
 [0.33333333]]
..............................
L22 : 
[[1.   0.  ]
 [1.25 1.  ]]
..............................


In [11]:
#print our matrixes
print("U : ")
print(U_finder(matrix))
print("..............................")
print("U11 : ")
print(U11(matrix))
print("..............................")
print("U12 : ")
print(U12(matrix))
print("..............................")
print("U22 : ")
print(U_finder(matrix22(matrix) - L21U12(matrix)))
print("..............................")

U : 
[[ 9.  3.  3.]
 [ 0. 16. 20.]
 [ 0.  0. 81.]]
..............................
U11 : 
[[9.]]
..............................
U12 : 
[[3. 3.]]
..............................
U22 : 
[[16. 20.]
 [ 0. 81.]]
..............................


In [12]:
#print our matrixes
print("L21 * U12 : ")
print(L21U12(matrix))
print("..............................")
print("L22 * U22 : ")
print(matrix22(matrix) - L21U12(matrix))

L21 * U12 : 
[[1. 1.]
 [1. 1.]]
..............................
L22 * U22 : 
[[ 16.  20.]
 [ 20. 106.]]


In [13]:
#print the result
print("RESULT :")
print()
print("our matrix :")
print(matrix)
print()
print("L decoposition :")
print(L_finder(matrix))
print()
print("U decomposition :")
print(U_finder(matrix))

RESULT :

our matrix :
[[  9.   3.   3.]
 [  3.  17.  21.]
 [  3.  21. 107.]]

L decoposition :
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 1.25       1.        ]]

U decomposition :
[[ 9.  3.  3.]
 [ 0. 16. 20.]
 [ 0.  0. 81.]]
